### ISSUE TITLE
AwesomeBackend.Database fail

### ISSUE THREAD

**Issue by dcube9** [marcominerva/AwesomeBackend#1]
I have run project AwesomeBackend.Database but it fail because field Restaurants.CreateAt is mandatory but in INSERT in file Script.PostDeployment.sql is missing.
I have tried 2 quick fixes :
1) Make filed Nullable
2) Add default value to CURRENT_TIMESTAMP (my choise)
Best regards
Paolo

**Comment by marcominerva** [comment]
Thank you for this, I have just updated the Database project adding a default value for the CreatedAt column of the Resturants table.
