### ISSUE TITLE
DefaultConnection doesnt match

### ISSUE THREAD

**Issue by dcube9** [marcominerva/AwesomeBackend#2]
AwesomeBackend.Database create Database in "(localdb)\ProjectsV13" but AwesomeBackend looking for database in (localdb)\mssqllocaldb.

I have modify mine in appsettings.json :
```
"DefaultConnection": "Server=(localdb)\\ProjectsV13;Database=AwesomeBackend.Database;Trusted_Connection=True;MultipleActiveResultSets=true",
"DefaultConnection.Original": "Server=(localdb)\\mssqllocaldb;Database=AwesomeDatabase;Trusted_Connection=True;MultipleActiveResultSets=true"
```

Is it possibile to set db location in project AwesomeBackend.Database ?

Grazie
Paolo

**Comment by marcominerva** [comment]
The **AwesomeBackend.Database** project doesn't specify a default publish location: it's up to you to decide where to publish the database when using the **Publish Database** wizard. The available locations depend on your system (i.e., you could have only LocalDB, or want to deploy the database to a local SQL EXPRESS or to a full SQL Server installed on your PC), so there is no guarantee that a default one would work for everyone.

In the `appsettings.json` file I have inserted a sample using **(localdb)\mssqllocaldb** that is the instance of LocalDB installed with Visual Studio. You can try running the command

`sqllocaldb info `

at the Dveloper Command Prompt  and see what instances of LocalDB you have installed on your PC. If you don't see an instance named **MSSQLLocalDB**, try following this article: https://medium.com/cloudnimble/upgrade-visual-studio-2019s-localdb-to-sql-2019-da9da71c8ed6.

**Comment by dcube9** [comment]
Grazie Marco.

In my PC I have 3 localdb :
![image](https://user-images.githubusercontent.com/10657031/104127822-8cdc1280-5364-11eb-8b41-524d3fb812fe.png)

But when I run it from VS2019 :
![image](https://user-images.githubusercontent.com/10657031/104127855-c44abf00-5364-11eb-8c78-fbee75887ed8.png)

Database is created in ProjectV13 :
![image](https://user-images.githubusercontent.com/10657031/104127916-0bd14b00-5365-11eb-8202-b464bdd01172.png)

So I dont know why AwesomeBackend.Database choises ProjectsV13.

**Comment by marcominerva** [comment]
When you start the **Publish Database** wizard (right click on the project, then **Publish**), you need to choose where to publish the database:

![image](https://user-images.githubusercontent.com/3522534/104128674-4b019b00-5369-11eb-9fbb-3570cb7935db.png)

**Comment by dcube9** [comment]
Ok, now run well.
My mistake is to run AwesomeBackend.Database instead of publish it.
Thank you.

PS: Notevoli le tue live twitch ripostate in youtube !

**Comment by marcominerva** [comment]
Grazie, allora conto che continuerai a seguirmi ;-)
